kind: pipeline
type: docker
name: default

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache/node_modules/

steps:
  - name: build
    image: node:18-bullseye-slim
    volumes:
      - name: cache
        path: /drone/src/node_modules/
    commands:
      # Set timezone to Taipei
      - ln --force --symbolic /usr/share/zoneinfo/Asia/Taipei /etc/localtime
      - dpkg-reconfigure --frontend noninteractive tzdata

      # Clone soda-web
      # Checkout to pre-production or production branch

      # Install dependencies and build
      - npm install
      - npm run build:staging

  # Test every commits
  - name: test
    image: node:18-bullseye
    commands:
      # Set timezone to Taipei
      - ln --force --symbolic /usr/share/zoneinfo/Asia/Taipei /etc/localtime
      - dpkg-reconfigure --frontend noninteractive tzdata

      # Dummy test
      - cd ./dist/
      - ls -l
