kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:18-bullseye-slim
    commands:
      - touch test.txt

  # Test every commits
  - name: test
    image: node:18-bullseye
    commands:
      - ls
