kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:18-bullseye-slim
    commands:
      - npm install
      - npm run build

  # Test every commits
  - name: test
    image: node:18-bullseye
    commands:
      - cd ./public/
      - ll
